### 회원가입
POST localhost:8080/signup
Content-Type: application/json

{
  "username": "JIN HO",
  "password": "12341234",
  "nickname": "Mentos"
}

### 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "username": "JIN HO",
  "password": "12341234"
}

### 관리자 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

### 관리자 권한 부여
PATCH localhost:8080/admin/users/2/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiQURNSU4iLCJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NzEyNTYyMSwiZXhwIjoxNzQ3MTI5MjIxfQ.msvg5wdIxc8b9tlF9w5bPjmj99wIISszTlFYaKe_imU