name: Run Test

on:
  push:
    branches: [ develop, feature/*, fix/*, refactor/*]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run All Tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean test
